general = {
  name = "XIAOAI";
  password = "3811";
  output_backend = "stdout";
  interpolation = "basic";
  volume_range_db = 30;
};

sessioncontrol = {
  allow_session_interruption = "yes";
  session_timeout = 20;
};
